In [18]:
import numpy as np
data = np.load(r"C:\Users\OmeN_HP\Desktop\Chess_project\numpy_saved\chess_board_Box.npz")


In [19]:
print(data.files)



['boxes']


In [20]:
arr1 = data['boxes']  # Замените 'array1' на нужное имя

print(arr1.shape)



(8, 8, 4)


In [21]:
print(arr1)

[[[316 154 371 201]
  [377 153 437 201]
  [441 151 502 201]
  [503 152 566 203]
  [565 153 632 201]
  [627 150 698 200]
  [692 151 762 199]
  [757 151 832 198]]

 [[304 201 368 254]
  [371 201 434 256]
  [437 201 501 256]
  [502 201 568 256]
  [566 203 638 256]
  [632 201 705 253]
  [698 200 774 255]
  [762 199 844 254]]

 [[301 254 362 312]
  [368 254 432 312]
  [434 256 501 312]
  [501 256 570 312]
  [568 256 640 312]
  [638 256 710 312]
  [705 253 781 311]
  [774 255 853 311]]

 [[294 314 357 374]
  [362 312 427 373]
  [432 312 498 374]
  [501 312 572 373]
  [570 312 644 374]
  [640 312 717 373]
  [710 312 792 375]
  [781 311 872 376]]

 [[285 376 349 440]
  [357 374 423 441]
  [427 373 498 440]
  [498 374 573 439]
  [572 373 649 439]
  [644 374 725 441]
  [717 373 802 441]
  [792 375 882 442]]

 [[273 442 341 513]
  [349 440 420 510]
  [423 441 497 511]
  [498 440 576 510]
  [573 439 653 512]
  [649 439 732 513]
  [725 441 813 512]
  [802 441 892 514]]

 [[266 511 333 588]
  [341 5

In [13]:
print(arr1)

[[[316 154 371 201]
  [377 153 437 201]
  [441 151 502 201]
  [503 152 566 203]
  [565 153 632 201]
  [627 150 698 200]
  [692 151 762 199]
  [757 151 832 198]]

 [[304 201 368 254]
  [371 201 434 256]
  [437 201 501 256]
  [502 201 568 256]
  [566 203 638 256]
  [632 201 705 253]
  [698 200 774 255]
  [762 199 844 254]]

 [[301 254 362 312]
  [368 254 432 312]
  [434 256 501 312]
  [501 256 570 312]
  [568 256 640 312]
  [638 256 710 312]
  [705 253 781 311]
  [774 255 853 311]]

 [[294 314 357 374]
  [362 312 427 373]
  [432 312 498 374]
  [501 312 572 373]
  [570 312 644 374]
  [640 312 717 373]
  [710 312 792 375]
  [781 311 872 376]]

 [[285 376 349 440]
  [357 374 423 441]
  [427 373 498 440]
  [498 374 573 439]
  [572 373 649 439]
  [644 374 725 441]
  [717 373 802 441]
  [792 375 882 442]]

 [[273 442 341 513]
  [349 440 420 510]
  [423 441 497 511]
  [498 440 576 510]
  [573 439 653 512]
  [649 439 732 513]
  [725 441 813 512]
  [802 441 892 514]]

 [[266 511 333 588]
  [341 5